### PR TITLE
Tested on hardware: Feature diffbase control and odometry

### PR DESCRIPTION
**Pull request by SyrianSpock**
Ready to merge.

What's been done:
- Tune PIDs of the wheelbase motors
- Implement odometry publisher
- Implement steering interface to control the wheelbase in velocity

PS: Odometry module has been merged into repo as subtree.

### CODE REVIEW

**Comment by antoinealb** [comment]
We still need to test odometry and steering interface, right ?

Also I think we should integrate odometry tests into the test build.

**Comment by SyrianSpock** [comment]
Yup. 
I agree for the tests, can you look into that ?

**Comment by antoinealb** [comment]
Sure I will take a look

**Comment by SyrianSpock** [comment]
Tested. Works. Ready to merge.

**Pull request merged**
